# Generated by Django 6.0.4 on 2026-05-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0009_alter_presupuesto_estado_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('online', 'Online'), ('taller', 'Taller')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('espera', 'Espera'), ('pendiente_medicion', 'Pendiente medición'), ('medicion_realizada', 'Medición realizada'), ('materiales', 'Materiales'), ('produccion', 'Produccion'), ('finalizado', 'Finalizado')], max_length=30)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto', to='presupuestos.presupuesto')),
            ],
        ),
    ]
