# Generated by Django 6.0.4 on 2026-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_detalles_proyecto_direccion_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='entrega',
            field=models.CharField(choices=[('Recogida', 'recogida'), ('Envio', 'envio'), ('Montar', 'montar')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente pago'), ('espera', 'Espera'), ('pendiente_medicion', 'Pendiente medición'), ('medicion_realizada', 'Medición realizada'), ('materiales', 'Materiales'), ('produccion', 'Produccion'), ('finalizado', 'Finalizado')], default='pendiente_pago', max_length=30),
        ),
    ]
