# Generated by Django 6.0.4 on 2026-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_entrega_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente pago'), ('revision', 'Revision'), ('pendiente_medicion', 'Pendiente medición'), ('medicion_realizada', 'Medición realizada'), ('materiales', 'Materiales'), ('produccion', 'Produccion'), ('finalizado', 'Finalizado')], default='pendiente_pago', max_length=30),
        ),
    ]
