# Generated by Django 6.0.4 on 2026-05-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente pago'), ('pendiente_cita', 'Pendiente cita'), ('revision', 'Revision'), ('materiales', 'Materiales'), ('produccion', 'Produccion'), ('finalizado', 'Finalizado')], default='pendiente_pago', max_length=30),
        ),
    ]
