# Generated by Django 6.0.4 on 2026-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
