# Generated by Django 6.0.4 on 2026-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_proyecto_fecha_confirmacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente pago'), ('pendiente_cita', 'Pendiente cita'), ('revision', 'Revision'), ('materiales', 'Materiales'), ('esperando_materiales', 'Esperando materiales'), ('produccion', 'Produccion'), ('finalizado', 'Finalizado')], default='pendiente_pago', max_length=30),
        ),
    ]
