# Generated by Django 6.0.4 on 2026-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente pago'), ('pendiente_cita', 'Pendiente cita'), ('revision', 'Revision'), ('materiales', 'Materiales'), ('esperando_materiales', 'Esperando materiales'), ('produccion', 'Produccion'), ('listo_envio', 'Listo para enviar'), ('listo_recogida', 'Listo para recoger en el taller'), ('listo_montaje', 'Listo para montar'), ('enviado', 'Enviado'), ('montaje', 'Montaje'), ('finalizado', 'Finalizado')], default='pendiente_pago', max_length=30),
        ),
    ]
