# Generated by Django 6.0.4 on 2026-06-15 09:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_proyecto_fecha_limite_pago_alter_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 30, 9, 59, 17, 121149, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
