# Generated by Django 6.0.4 on 2026-06-03 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0010_fianza_presupuesto_fianza'),
        ('proyectos', '0006_proyecto_fecha_confirmacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(choices=[('pedir_material', 'Pedir Materiales'), ('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar')], max_length=20, unique=True)),
                ('tiempo_estimado_horas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TareasProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedir_material', 'Pedir Materiales'), ('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada')], default='pendiente', max_length=20)),
                ('tiempo_estimado_horas', models.FloatField()),
                ('orden', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('depende_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tareasproyecto')),
                ('linea_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.lineapresupuesto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
