# Generated by Django 6.0.4 on 2026-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasproyecto',
            name='tipo',
            field=models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tiempotarea',
            name='proceso',
            field=models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar')], max_length=20, unique=True),
        ),
    ]
