# Generated by Django 6.0.4 on 2026-06-04 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0010_fianza_presupuesto_fianza'),
        ('proyectos', '0007_alter_proyecto_estado'),
        ('tareas', '0002_alter_tareasproyecto_tipo_alter_tiempotarea_proceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada')], default='pendiente', max_length=20)),
                ('tiempo_estimado_horas', models.FloatField()),
                ('orden', models.IntegerField(default=0)),
                ('bloqueada', models.BooleanField(default=False)),
                ('fecha_inicio_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('depende_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea')),
                ('linea_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='presupuestos.lineapresupuesto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TareasProyecto',
        ),
    ]
