# Generated by Django 6.0.4 on 2026-06-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0010_fianza_presupuesto_fianza'),
        ('tareas', '0003_tarea_delete_tareasproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='trabajadores_montaje',
            field=models.ManyToManyField(blank=True, null=True, related_name='tareas_grupales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='linea_presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='presupuestos.lineapresupuesto'),
        ),
    ]
