# Generated by Django 6.0.4 on 2026-06-07 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_trabajadores_montaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='trabajadores_montaje',
            field=models.ManyToManyField(blank=True, related_name='tareas_grupales', to=settings.AUTH_USER_MODEL),
        ),
    ]
