# Generated by Django 6.0.4 on 2026-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_tarea_trabajadores_montaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar'), ('montaje', 'Montaje')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tiempotarea',
            name='proceso',
            field=models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar'), ('montaje', 'Montaje')], max_length=20, unique=True),
        ),
    ]
