# Generated by Django 6.0.4 on 2026-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_tarea_tipo_alter_tiempotarea_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar'), ('montaje', 'Montaje'), ('preparar_envio', 'Preparar envio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tiempotarea',
            name='proceso',
            field=models.CharField(choices=[('cortar', 'Cortar'), ('mecanizar', 'Mecanizar'), ('montar', 'Montar'), ('ensamblar', 'Ensamblar'), ('montaje', 'Montaje'), ('preparar_envio', 'Preparar envio')], max_length=20, unique=True),
        ),
    ]
