# Generated by Django 6.0.4 on 2026-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_tarea_tipo_alter_tiempotarea_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada'), ('candelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
