# Generated by Django 6.0.4 on 2026-05-16 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0009_alter_opcion_precio_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OpcioneSeleccionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linea_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_seleccionadas', to='presupuestos.lineapresupuesto')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.opcion')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_obra', models.CharField(max_length=300)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Borrador', 'borrador'), ('Pendiente', 'pendiente'), ('Confirmado', 'confirmado'), ('Produccion', 'produccion'), ('Finalizado', 'finalizado'), ('Cancelado', 'cancelado')], default='Borrador', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineapresupuesto',
            name='Presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='presupuestos.presupuesto'),
        ),
    ]
