# Generated by Django 6.0.4 on 2026-05-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
        ('productos', '0009_alter_opcion_precio_extra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpcioneSeleccionada',
            new_name='OpcionSeleccionada',
        ),
        migrations.RenameField(
            model_name='lineapresupuesto',
            old_name='Presupuesto',
            new_name='presupuesto',
        ),
    ]
