# Generated by Django 6.0.4 on 2026-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_rename_opcioneseleccionada_opcionseleccionada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('distancia_maxima', models.FloatField(help_text='Distancia máxima permitida en km')),
            ],
            options={
                'verbose_name': 'Configuración de Distancia',
                'verbose_name_plural': 'Configuración de Distancia',
            },
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='precio_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_entrega',
            field=models.CharField(choices=[('Recogida', 'recogida'), ('Envio', 'envio'), ('Montar', 'montar')], default='Recogida', max_length=20),
        ),
    ]
