# Generated by Django 6.0.4 on 2026-05-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_distancia_presupuesto_precio_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='direccion_obra',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='longitud',
        ),
    ]
