# Generated by Django 6.0.4 on 2026-05-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_remove_presupuesto_direccion_obra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapresupuesto',
            old_name='Producto',
            new_name='producto',
        ),
    ]
