# Generated by Django 6.0.4 on 2026-05-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_rename_producto_lineapresupuesto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='tipo_entrega',
        ),
    ]
