# Generated by Django 6.0.4 on 2026-05-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_remove_presupuesto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='precio_entrega',
        ),
    ]
