# Generated by Django 6.0.4 on 2026-05-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_remove_presupuesto_precio_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado_pagado',
            field=models.CharField(choices=[('sin_pagar', 'Sin pagar'), ('procesando', 'Procesando pago'), ('pagado', 'Pagado')], default='sin_pagar', max_length=20),
        ),
    ]
