# Generated by Django 6.0.4 on 2026-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0008_presupuesto_estado_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estado_pagado',
            field=models.CharField(choices=[('sin_pagar', 'Sin pagar'), ('procesando', 'Procesando pago'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='sin_pagar', max_length=20),
        ),
    ]
