# Generated by Django 6.0.4 on 2026-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_alter_presupuesto_estado_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fianza',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('porcentaje', models.FloatField(help_text='porcentaje que se paga de fianza (%)')),
            ],
            options={
                'verbose_name': 'Configuración de Fianza',
                'verbose_name_plural': 'Configuración de Fianza',
            },
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fianza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
