# Generated by Django 6.0.4 on 2026-05-05 15:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
    ]
