# Generated by Django 6.0.4 on 2026-05-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_auto_20260505_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='productos.caracteristica')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='productos.producto'),
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='productos.caracteristica')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.habitacion')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='productos.opcion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('caracteristica', 'habitacion'), name='una_recomendacion_por_habitacion')],
            },
        ),
    ]
