# Generated by Django 6.0.4 on 2026-05-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
