# Generated by Django 6.0.4 on 2026-05-10 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_opcion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='productos.habitacion'),
        ),
    ]
