# Generated by Django 6.0.4 on 2026-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_opcion_descripcion_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
