# Generated by Django 6.0.4 on 2026-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_caracteristica_nombre_alter_opcion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='caracteristica',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='unique_caracteristica_producto'),
        ),
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(fields=('caracteristica', 'nombre'), name='unique_opcion_caracteristica'),
        ),
    ]
