# Generated by Django 6.0.4 on 2026-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_caracteristica_nombre_alter_opcion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
