# Generated by Django 6.0.4 on 2026-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_opcion_precio_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre',), name='unique_producto_activo'),
        ),
    ]
