# Generated by Django 6.0.4 on 2026-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='horario',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
