# Generated by Django 6.0.4 on 2026-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
