# Generated by Django 6.0.4 on 2026-06-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0005_alter_proyecto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasCandelacion',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('dias_canelacion_cita', models.IntegerField(help_text='Días permitidos para cancelar antes de la fecha')),
            ],
            options={
                'verbose_name': 'Días permitidos para cancelar antes de la fecha',
                'verbose_name_plural': 'Días permitidos para cancelar antes de la fecha',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='disponible', max_length=20)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='proyectos.proyecto')),
            ],
        ),
    ]
