# Generated by Django 6.0.4 on 2026-06-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_proyecto'),
        ('proyectos', '0005_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita', to='proyectos.proyecto'),
        ),
    ]
