# Generated by Django 6.0.4 on 2026-07-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiasCandelacion',
            new_name='DiasCancelacion',
        ),
    ]
