# Generated by Django 6.0.4 on 2026-07-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_rename_diascandelacion_diascancelacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diascancelacion',
            old_name='dias_canelacion_cita',
            new_name='dias_cancelacion_cita',
        ),
    ]
